name: Build MobileLang Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build with Buildozer
      uses: ArtemS-G/buildozer-action@v1.2
      with:
        workdir: .
        buildozer_version: master

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MobileLang-APK
        path: bin/*.apk
